# SERVER
server.port=5000
server.address=0.0.0.0


# Force Spring Security to stop generating a random password
spring.security.user.name=admin
spring.security.user.password=disable


# DATABASE (AWS RDS)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/turingchatdb}
spring.datasource.username=${DB_USERNAME:turingchat}
spring.datasource.password=${DB_PASSWORD:1245}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# CLAUDE API
claude.api.key=${CLAUDE_API_KEY}

# FRONTEND (S3 + CloudFront)
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true